# Autogenerated wrapper script for jd_jll for x86_64-w64-mingw32
export jd

JLLWrappers.@generate_wrapper_header("jd")
JLLWrappers.@declare_executable_product(jd)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        jd,
        "bin\\jd.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
